### ISSUE TITLE
how to get the date from time_point in contract?

### ISSUE THREAD

**Issue by cppfuns** [EOSIO/eosio.cdt#331] opened 2018-12-24 12:02 UTC
I want to calculate the current time, the time difference between the zeros of the day.
It may take time_point to convert to the year, month, and day methods, and clear (hours, minutes, seconds) to the difference.

**Comment by prem-baranwal** [comment] 2018-12-28 07:45
I have a similar issue where i need to read date/time from user and save it as seconds (time_t) in table. However, when i use mktime(), i get error **_"error: use of undeclared identifier 'mktime'; did you mean 'gmtime'?"_** and where i use a non-standard alternative timegm(), compilation is fine but wasm-ld gives error _**"error: pademo.wasm: undefined symbol: timegm"**_
Someone, please help. Its the basic time operation that seems not supported in the wasm generator.
Note: I also saw a commit where mktime was removed. Not sure why.

**Comment by maoueh** [comment] 2019-01-01 14:57
I don't think there is methods to transform [time_point](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/time.hpp#L38) nor [time_point_sec](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/time.hpp#L62) to their date representation counterpart. The WASM interface for the smart contract does not have that and it makes little sense IMO when coding a smart contract anyway.

To have a `time_point` or `time_point_sec` initiated at current time, use [current_time](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/system.h#L79) (microseconds) or [now](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/system.h#L86) (seconds) from the [system.h](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/system.h) header.

```
#include <eosiolib/time.hpp>
#include <eosiolib/system.h>

auto nowWithMicroseconds = time_point(current_time())
auto nowWithSeconds = time_point_sec(now())
```

Store in your smart contract's table your timestamp using either `time_point` or `time_point_sec` depending on your needs. When you will query back the data using `cleos` or using the REST API directly, `nodeos` will automatically convert it to a date string representation of the timestamp for you.

```
$ cleos get table eosforumrcpp eosforumrcpp proposal --limit 1
{
  "rows": [{
      "proposal_name": "",
      "proposer": "gyztimzshage",
      "title": "啊",
      "proposal_json": "{\"content\":\"\",\"type\":\"\"}",
      "created_at": "2018-12-10T17:15:29",
      "expires_at": "2019-01-09T00:00:00"
    }
  ],
  "more": true
}
```

The `created_at` and `expires_at` fields are `time_point_sec` object inside the contract ([see here](https://github.com/eoscanada/eosio.forum/blob/master/include/forum.hpp#L85)), as you can see, they are however turned into date string representation automatically when requesting in JSON form.

@prem-baranwal Use `time_point` and `time_point_sec` objects in your smart contract implementation and `time_point(current_time())` and `time_point_sec(now())` to instantiate the object to current time value. Check the [time.hpp](https://github.com/EOSIO/eosio.cdt/blob/master/libraries/eosiolib/time.hpp) file to see how you can manipulate each object.

See #340 for a similar error and further explanation about the error.

Hope it helps.

**Comment by jeffreyssmith2nd** [comment] 2019-07-17 14:03
Closing this as it seems like the issue is resolved. Feel free to reopen if there are further questions/issues.

**Closed by jeffreyssmith2nd** 2019-07-17 14:03 UTC
