### ISSUE TITLE
eosio.wasmsdk/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc: No such file or directory

### ISSUE THREAD

**Issue by noprom** [EOSIO/eosio.cdt#73] opened 2018-09-05 14:26 UTC
While I was building it on a Mac OSX with 8 core and 16G RAM, I run:
```
./build.sh EOS
```
The following errors occured:
```
Scanning dependencies of target llvm-exegesis
[100%] Building CXX object tools/llvm-exegesis/CMakeFiles/llvm-exegesis.dir/llvm-exegesis.cpp.o
[100%] Linking CXX shared module ../../lib/BugpointPasses.dylib
[100%] Built target BugpointPasses
[100%] Linking CXX executable ../../bin/llvm-objdump
[100%] Built target llvm-objdump
[100%] Linking CXX executable ../../bin/llvm-xray
[100%] Linking CXX executable ../../bin/llvm-exegesis
[100%] Built target llvm-xray
[100%] Built target llvm-exegesis
[100%] Linking CXX executable ../../bin/opt
[100%] Built target opt
[ 12%] No install step for 'EosioClang'
[ 12%] No test step for 'EosioClang'
[ 12%] Completed 'EosioClang'
[ 12%] Built target EosioClang
Scanning dependencies of target c
[ 13%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_r.c.o
[ 13%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_md5.c.o
[ 13%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_sha256.c.o
[ 13%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_des.c.o
[ 13%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt.c.o
[ 13%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_sha512.c.o
[ 13%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_blowfish.c.o
[ 13%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/encrypt.c.o
/bin/sh: /Users/noprom/Documents/Dev/BlockChain/OS/eosio.wasmsdk/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc: No such file or directory
/bin/sh: /Users/noprom/Documents/Dev/BlockChain/OS/eosio.wasmsdk/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc: No such file or directory
/bin/sh: /Users/noprom/Documents/Dev/BlockChain/OS/eosio.wasmsdk/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc: No such file or directory
/bin/sh: /Users/noprom/Documents/Dev/BlockChain/OS/eosio.wasmsdk/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc: No such file or directory
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_des.c.o] Error 127
/bin/sh: /Users/noprom/Documents/Dev/BlockChain/OS/eosio.wasmsdk/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc: No such file or directory
/bin/sh: /Users/noprom/Documents/Dev/BlockChain/OS/eosio.wasmsdk/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc: No such file or directory
/bin/sh: /Users/noprom/Documents/Dev/BlockChain/OS/eosio.wasmsdk/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc: No such file or directory
make[2]: *** Waiting for unfinished jobs....
/bin/sh: /Users/noprom/Documents/Dev/BlockChain/OS/eosio.wasmsdk/build/EosioClang-prefix/src/EosioClang-build/bin/eosio-cc: No such file or directory
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_blowfish.c.o] Error 127
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_md5.c.o] Error 127
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_sha256.c.o] Error 127
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_sha512.c.o] Error 127
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt_r.c.o] Error 127
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/encrypt.c.o] Error 127
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt.c.o] Error 127
make[1]: *** [libraries/libc/CMakeFiles/c.dir/all] Error 2
make: *** [all] Error 2
```

Anyone know why this happened?
Any help would be appreciated.

**Comment by spartucus** [comment] 2018-09-06 10:27
same here.

**Comment by larryk85** [comment] 2018-09-20 18:16
Should be resolved in v1.2.1

**Closed by larryk85** 2018-09-20 18:16 UTC

**Comment by onigirisan** [comment] 2018-09-27 04:35
@larryk85 Same error in v1.2.1

**Comment by noprom** [comment] 2018-09-29 05:47
@larryk85  still get error on `1.2.1`.

**Comment by mosasiru** [comment] 2018-10-10 01:03
@larryk85 still same error on 1.2.1.

**Comment by wangai** [comment] 2018-10-10 06:14
@larryk85 still same error on 1.2.1
ubuntu 16.04 lts
intel i5 7300hq 8gb

**Comment by RoshanSyed** [comment] 2018-10-11 19:44
I am experiencing a similar issue with both trying to build the latest version and also the tagged 1.2.0:  

`[ 12%] Building C object libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt.c.o
Segmentation fault (core dumped)
libraries/libc/CMakeFiles/c.dir/build.make:62: recipe for target 'libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt.c.o' failed
make[2]: *** [libraries/libc/CMakeFiles/c.dir/musl/src/crypt/crypt.c.o] Error 139
CMakeFiles/Makefile2:1123: recipe for target 'libraries/libc/CMakeFiles/c.dir/all' failed
make[1]: *** [libraries/libc/CMakeFiles/c.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2`

Using: 
Ubuntu 16.04
4 cores
8GB RAM 1GB Swap
61GB Disk Space Available

My steps were as follows:

1st try:
`git clone --recursive https://github.com/eosio/eosio.cdt
cd eosio.cdt
git checkout v1.2.0
git submodule update --recursive
./build EOS`

2nd try:
`git clone --recursive https://github.com/eosio/eosio.cdt
cd eosio.cdt
./build EOS`

Both yielded in the above error.

**Comment by larryk85** [comment] 2018-10-11 20:16
Debian packages are available, for the latest release.  @RoshanSyed, yours seems to be an issue with GCC seg faulting, this is an issue with your core compiler.  If you really want to compile from source, you can download and build a different version of GCC or use Clang.

**Comment by RoshanSyed** [comment] 2018-10-12 11:53
@larryk85 Same error reproduces when trying to build with Clang 4.0
