### ISSUE TITLE
eosio-cpp has been stuck

### ISSUE THREAD

**Issue by ancjf** [EOSIO/eosio.cdt#446] opened 2019-03-13 09:31 UTC
wget https://github.com/eosio/eosio.cdt/releases/download/v1.5.0/eosio.cdt_1.5.0-1_amd64.deb
apt install ./eosio.cdt_1.5.0-1_amd64.deb

con.cpp：

	#include <eosiolib/eosio.hpp>

	class [[eosio::contract]] con : public eosio::contract {
	public:
		using contract::contract;
		[[eosio::action]] void act()
		{
		}
	};

	EOSIO_DISPATCH(con, (act))

eosio-cpp con.cpp -o con.wasm --abigen

Has been stuck. Who can help me?

cpuinfo:

	processor	: 0
	vendor_id	: GenuineIntel
	cpu family	: 6
	model		: 158
	model name	: Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
	stepping	: 9
	microcode	: 0x84
	cpu MHz		: 3600.000
	cache size	: 8192 KB
	physical id	: 0
	siblings	: 1
	core id		: 0
	cpu cores	: 1
	apicid		: 0
	initial apicid	: 0
	fpu		: yes
	fpu_exception	: yes
	cpuid level	: 22
	wp		: yes
	flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon nopl xtopology tsc_reliable nonstop_tsc cpuid pni pclmulqdq ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single pti ibrs ibpb stibp fsgsbase tsc_adjust bmi1 hle avx2 smep bmi2 invpcid rtm mpx rdseed adx smap clflushopt xsaveopt xsavec xsaves arat arch_capabilities
	bugs		: cpu_meltdown spectre_v1 spectre_v2 spec_store_bypass l1tf
	bogomips	: 7200.00
	clflush size	: 64
	cache_alignment	: 64
	address sizes	: 43 bits physical, 48 bits virtual
	power management:
	
System info:	

	No LSB modules are available.
	Distributor ID:	Ubuntu
	Description:	Ubuntu 18.04.2 LTS
	Release:	18.04
	Codename:	bionic

Using wmware 14

**Comment by maoueh** [comment] 2019-03-13 14:41
Most probably a duplicate of https://github.com/EOSIO/eosio.cdt/issues/288, having only one core in a virtual machine seems to cause the compiler to never complete. Add at least two cores.

Should be closed IMO.

**Comment by larryk85** [comment] 2019-03-13 17:10
Thank you @maoueh, yes this appears to be a duplicate of #288.  Set the number of cpu cores to > 1 and this should fix your issue.

**Closed by larryk85** 2019-03-13 17:10 UTC
