### ISSUE TITLE
Using tuple in multi index tables causes Segmentation Fault: 11

### ISSUE THREAD

**Issue by jonericcook** [EOSIO/eosio.cdt#521] opened 2019-05-21 15:02 UTC
@larryk85 

**eosio-cpp version**
```
Work-MacBook-Pro:~ joneric.cook$ eosio-cpp --version
eosio-cpp version 1.6.1
```

**hello.cpp**
```
#include <eosio/eosio.hpp>
#include <eosio/print.hpp>
#include <tuple>

using std::tuple;
using namespace eosio;

class[[eosio::contract("hello")]] hello : public contract
{
public:
   using contract::contract;

   [[eosio::action]] void hi(name user) {
      require_auth(user);
      print("Hello, ", user);
   }

   struct [[eosio::table]] greeting {
      uint64_t id;
      // tuple<int, int> t;
      uint64_t primary_key() const { return id; }
   };
   typedef multi_index<"greeting"_n, greeting> greeting_index;
};
```

**compile**
```
Work-MacBook-Pro:hello joneric.cook$ eosio-cpp -abigen -contract hello -o hello.wasm src/hello.cpp
Warning, empty ricardian clause file
Warning, empty ricardian clause file
Warning, action <hi> does not have a ricardian contract
Segmentation fault: 11
```

**Comment by jeffreyssmith2nd** [comment] 2019-07-17 15:35
Confirmed happening in 1.6.2

**Comment by jeffreyssmith2nd** [comment] 2019-07-18 16:45
If I modify your contract to the following, it compiles and builds the abi as expected.

Note that all I did was remove `using std::tuple;` and prefix tuple with `std::`
```
#include <eosio/eosio.hpp>
#include <eosio/print.hpp>
#include <tuple>

using namespace eosio;

class[[eosio::contract("hello")]] hello : public contract
{
public:
   using contract::contract;

   [[eosio::action]] void hi(name user) {
      require_auth(user);
      print("Hello, ", user);
   }

   struct [[eosio::table]] greeting {
      uint64_t id;
      std::tuple<int, int> t;
      uint64_t primary_key() const { return id; }
   };
   typedef multi_index<"greeting"_n, greeting> greeting_index;
};
```

**Comment by jeffreyssmith2nd** [comment] 2019-07-18 16:56
Since the error is actually with the using-declaration, closing this issue in favor of Issue #558 that specifically tracks this problem.

**Closed by jeffreyssmith2nd** 2019-07-18 16:56 UTC
Labels: bug
