### ISSUE TITLE
CDT does not generate correct ABI type for vector with a custom struct.

### ISSUE THREAD

**Issue by dixia** [EOSIO/eosio.cdt#187] opened 2018-10-23 06:08 UTC
CDT does not generate correct ABI type for vector with a struct.

In the attached code, the type of the lock_asset is not correctly generated. I guess it is due to the type of vector is custom struct?

[lt_contract.abi.txt](https://github.com/EOSIO/eosio.cdt/files/2504695/lt_contract.abi.txt)
[lt_contract.cpp.txt](https://github.com/EOSIO/eosio.cdt/files/2504696/lt_contract.cpp.txt)
[lt_contract.hpp.txt](https://github.com/EOSIO/eosio.cdt/files/2504697/lt_contract.hpp.txt)

**Comment by dixia** [comment] 2018-10-23 06:09
discovered  by qui guacharo

**Comment by dixia** [comment] 2018-10-23 06:11
@WhoAmI233

**Comment by andriantolie** [comment] 2018-10-24 02:13
I check it with primitive type (uint32_t), and it also generates the same problem, i.e.
```
      typedef vector<uint32_t> vector_of_uint32;
      TABLE sample {
        vector_of_uint32 v;
      };
```
results in
```
    "types": [
        {
            "new_type_name": "vector_of_uint32",
            "type": ">"
        }
    ],
```
Seems the problem is more generic and not just specific to custom struct.

**Comment by lonkly** [comment] 2018-11-02 10:28
optional<vector<string>> does not work as well

**Comment by taokayan** [comment] 2018-11-05 10:04
> optional <vector < string > > does not work as well

We don't support ```optional<vector<string> >``` at the moment because the current abi_serializer can't decode ```string[]?```. The workaround is to make a struct as intermediate type.

**Comment by jeffreyssmith2nd** [comment] 2019-07-17 14:51
1.6.2 correctly handles the vector struct. Closing this issue in favor of #231 which can become the discussion place for the various nested containers and their support.

**Closed by jeffreyssmith2nd** 2019-07-17 14:51 UTC
Labels: bug
