### ISSUE TITLE
Question about "eosio-cpp -o hello.wasm hello.cpp --abigen"

### ISSUE THREAD

**Issue by heyuanchao** [EOSIO/eosio.cdt#123] opened 2018-10-03 10:05 UTC
when I use "eosio-cpp hello.cpp -o hello.wasm --abigen", it won't run correctly，I must use “Ctrl+C” to stop it，it is so weird，and no “hello.abi” generated

![image](https://user-images.githubusercontent.com/10580354/46404767-babf5f00-c738-11e8-88c1-477e62d5a3a8.png)

here is the hello.cpp
```
#include <eosiolib/eosio.hpp>
#include <eosiolib/print.hpp>

using namespace eosio;

class hello : public contract {
  public:
      using contract::contract;

      [[eosio::action]]
      void hi( account_name user ) {
         print( "Hello, ", name{user} );
      }
};
EOSIO_ABI( hello, (hi))
```

here is the system info:
![image](https://user-images.githubusercontent.com/10580354/46405982-98c7db80-c73c-11e8-8080-4e25999893e9.png)

**Comment by larryk85** [comment] 2018-10-03 14:19
The next release (v1.3) should resolve these issues.

**Comment by nsjames** [comment] 2018-10-10 15:07
@larryk85 
Any idea when the next release is, or a downgraded version we can use in the meantime?

**Comment by heyuanchao** [comment] 2018-10-11 10:00
@nsjames The new version（1.3.0） is available

**Comment by nsjames** [comment] 2018-10-13 12:47
Thanks @heyuanchao

**Comment by heyuanchao** [comment] 2018-10-14 07:17
@larryk85 v1.3.1 still have this problem

**Comment by larryk85** [comment] 2018-10-15 06:00
If you run `eosio-cpp -version` and `eosio-abigen -version` do these match and are they v1.3.1?

**Comment by heyuanchao** [comment] 2018-10-20 09:35
![image](https://user-images.githubusercontent.com/10580354/47254033-71884280-d48e-11e8-8a2b-e1b84d3f1b1c.png)

**Comment by heyuanchao** [comment] 2018-10-20 09:41
The reason is VirtualBox

**Comment by idnotbe** [comment] 2018-10-26 02:04
@heyuanchao 

i encountered the same error and i use : 
Ubuntu 18.04.1 on VMware (Windows 10 64bit)
EOSIO v1.4.1
eosio.cdt-1.3.2

how do you solve the problem? 
did you change some settings on VirtualBox? or just use Linux only computer?

**Comment by heyuanchao** [comment] 2018-10-26 06:49
@idnotbe i use Ubuntu 18.04.1 only computer at last

**Comment by agxmeister** [comment] 2018-10-30 15:49
I have experienced the same problem: on Ubuntu 18.04 on VirtualBox the compilation process is stuck. I created .wasm and .abi files, but it looks corrupted: attempts to upload it into blockchain failed with error related to .wasm inconsistency.

**Comment by dsbrother** [comment] 2018-10-31 09:10
Has this problem been resolved?
I use AWS's Ubuntu 18.04.1 LTS, the same problem is occurring.

**Comment by idnotbe** [comment] 2018-10-31 15:05
i solved this problem.
just do not use a virtual machine.
i completely formatted my computer and installed Ubuntu os.

**Comment by nsjames** [comment] 2018-10-31 19:50
> just do not use a virtual machine. 

This simply isn't an option. We need VM support for a lot of users.
Personally I can't just dual-boot ubuntu and work with eosio as it limits the programs I can run ( a lot of which do not run on Unix )

**Comment by ohweio** [comment] 2018-11-01 01:54
> i solved this problem.
> just do not use a virtual machine.
> i completely formatted my computer and installed Ubuntu os.

I do not use a virtual machine.
I use AWS EC2 Ubuntu 18.04.1 LTS 
but the same problem occurs

**Comment by pavja2** [comment] 2018-11-01 13:15
> > i solved this problem.
> > just do not use a virtual machine.
> > i completely formatted my computer and installed Ubuntu os.
> 
> I do not use a virtual machine.
> I use AWS EC2 Ubuntu 18.04.1 LTS
> but the same problem occurs

That's going to be virtualized on AWS's end of things so it means it's likely that there is some issue with the CDT and virtualization.

> > just do not use a virtual machine.
> 
> This simply isn't an option. We need VM support for a lot of users ( or at the very least windows support ).
> Personally I can't just dual-boot ubuntu and work with eosio as it limits the programs I can run ( a lot of which do not run on Unix )

I agree 100%. Requiring a native installation of the CDT on OS-X or Linux is really not a viable strategy. It also means that a lot of continuous integration and testing platforms won't be feasible to use which is a big barrier to good development down the line.

**Comment by hqblock** [comment] 2018-11-01 13:20
It also failed in a Digital Ocean server, I guess it's also a VM. But it worked installing Ubuntu in a local machine.

**Comment by whitenoiseL** [comment] 2018-11-06 03:45
Same problem. I run it in docker and eosio-cpp (version 1.3.2) hangs forever. Even if using cmake, it still hangs forever. Have anyone solved this?

**Comment by cenjinchang** [comment] 2018-11-14 11:34
Is anyone solved this ?

**Comment by larryk85** [comment] 2018-11-14 18:40
I have tried AWS, docker, virtualbox, parallels and windows subsystem for linux and I can't replicate this at all.  If anyone who is having this same problem could post VM settings (ram, cpu cores, etc.) that would help me figure out what is going wrong for you.

**Comment by pavja2** [comment] 2018-11-14 18:44
I have the issue running VMWare Workstation 14 with a clean install of Ubuntu 18.04 LTS. This issue appears both using the .deb and when building from source.  My VM is provisioned with 16GB of RAM (host has 32) and 2 cores (host has 16-ish depending on how you count). Let me know if there's any more info that might help - happy to try and get this debugged!

**Comment by nsjames** [comment] 2018-11-14 19:14
VirtualBox Win10 host, 16gb allocated, 60gb vdi, ubuntu 16.04. 

- Processor -- Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz, 3696 Mhz, 6 Core(s), 12 Logical Processor(s)

**Comment by cenjinchang** [comment] 2018-11-15 02:38
I upgrade virtual machine from Ubuntu 16.04. LTS to Ubuntu 18.04 ,this issue appears.  but the say settings in my partner's computer ,it doesn't appear.

**Comment by vingo555** [comment] 2018-11-17 06:52
> i solved this problem.
> just do not use a virtual machine.
> i completely formatted my computer and installed Ubuntu os.

Why the compiler need the real machine ? why it doesn't work inside VM ? 
I really doubt whether this the root cause for this issue.

**Comment by vingo555** [comment] 2018-11-17 07:17
I don't think this issue is really resolved. 
Have you tried the 1.3.1 or 1.4 ?  @larryk85

**Comment by larryk85** [comment] 2018-11-18 07:53
I have tried every version from 1.2.x to 1.4.x and we now have CI being added to the pipeline which also doesn't replicate this issue.  @vingo555 what are your specs for your vm? What virtualization software are you using?

**Comment by ciga2011** [comment] 2018-11-19 13:05
@larryk85 I cannot compile contract with eosio-cpp as well, it hangs forever ,never return back.  you can replicate the issue as following: 
1. pull official eos image: 
```
 docker pull eosio/eos:v1.4.3
```
2. start this image and get into the container, then  install official cdt 1.4.1 deb package:
```
$ wget https://github.com/eosio/eosio.cdt/releases/download/v1.4.1/eosio.cdt-fedora-1.4.1.x86_64-0.x86_64.rpm
$ sudo yum install ./eosio.cdt-fedora-1.4.1.x86_64-0.x86_64.rpm
```

3. copy hello sample into container and run eosio-cpp

```
$ eosio-cpp -o hello.wasm -abigen -v hello.cpp
```

now you replicate the issue : it will freeze here forever.

After some quick research, I found out the problem was related with eosio-ld ， if you exclude
the link phase, above command can return with an incomplete wasm(un-linked yet):

```
$ eosio-cpp -o hello.wasm -abigen -v -c hello.cpp
```

hope this information could help.

BTW: cdt document is really,really bad.

**Comment by akrsmv** [comment] 2018-11-22 08:32
> > i solved this problem.
> > just do not use a virtual machine.
> > i completely formatted my computer and installed Ubuntu os.
> 
> I do not use a virtual machine.
> I use AWS EC2 Ubuntu 18.04.1 LTS
> but the same problem occurs

Same here

**Comment by cddjr** [comment] 2018-11-23 08:44
> UPDATE ：
> 
> @larryk85 after some more research， I found out the issue is related with **cpu core numbers**: if the machine/vm has more than one cpu core, eosio-cpp works like a charm, but if only one cpu core exists, it will hang forever.
> 
> hope this information helps.

如果虚拟机的core=1，就会hang forever，@heyuanchao  将虚拟机设为多核即可避免此问题。

估计这年头还用单核的机子已经很少了，或者我们构建的虚拟机默认也不会是单核cpu，所以k85一直说无法重现bug，哈哈

**Comment by atulatul** [comment] 2018-11-25 14:52
Yeah I was also facing the same issue to compile one of dummy contract I was trying to create it took  a lot of time today to figure me out about the same issue the compiler always hanged.

But in my virtual machine I followed following steps and it could resolve the issue now it is able to compile and produce desired result.

Settings I tried :+1: 

Power off the virtual machine.
Right-click on the virtual machine and click Edit Settings.
Click Systems and select CPUs make it more than 1 
Choose the number of virtual processors

may be during cdt install we can have some way to notify about this to end user it would help for a vm user.

Cheers!

**Comment by ludosone** [comment] 2018-12-01 05:38
> UPDATE ：
> 
> @larryk85 after some more research， I found out the issue is related with **cpu core numbers**: if the machine/vm has more than one cpu core, eosio-cpp works like a charm, but if only one cpu core exists, it will hang forever.
> 
> hope this information helps.
> 
> @larryk85 I cannot compile contract with eosio-cpp as well, it hangs forever ,never return back. you can replicate the issue as following:
> 
> 1. pull official eos image:
> 
> ```
>  docker pull eosio/eos:v1.4.3
> ```
> 1. start this image and get into the container, then  install official cdt 1.4.1 deb package:
> 
> ```
> $ wget https://github.com/eosio/eosio.cdt/releases/download/v1.4.1/eosio.cdt-1.4.1.x86_64.deb
> $ sudo apt install ./eosio.cdt-1.4.1.x86_64.deb
> ```
> 1. copy hello sample into container and run eosio-cpp
> 
> ```
> $ eosio-cpp -o hello.wasm -abigen -v hello.cpp
> ```
> **now you replicate the issue : it will freeze here forever.**
> 
> After some quick research, I found out the problem was related with eosio-ld ， if you exclude
> the link phase, above command can return with an incomplete wasm(un-linked yet):
> 
> ```
> $ eosio-cpp -o hello.wasm -abigen -v -c hello.cpp
> ```
> hope this information could help.
> 
> BTW: cdt document is really,really bad.

Same here, using AWS ubuntu 18. the eosio-cpp never return, wasm and abi files somehow generated, but cannot be deployed to chain.

**Comment by larryk85** [comment] 2018-12-17 16:03
I have replicated the issue, but I don't have a fix available for this.  You need at least 2 cores or else the linker will hang indefinitely.  Will keep everyone posted if a fix is made available.

**Comment by santai87** [comment] 2018-12-20 06:36
@cddjr 答案是對的

VMware workstation 15 run Ubuntu-16.04 with 2 core CPU

This solution is work!

**Comment by trifist** [comment] 2018-12-23 08:33
I use the cheapest VPS which have only one core...
So is here any way to fix this problem, something like modify system parameters?
这不是坑爹了吗，双核的好贵。。

**Comment by cddjr** [comment] 2018-12-23 15:14
> I use the cheapest VPS which have only one core...
> So is here any way to fix this problem, something like modify system parameters?
> 这不是坑爹了吗，双核的好贵。。

那你只能在本地编译了

**Comment by LuminousXLB** [comment] 2019-04-29 16:53
I hvae exactly the same problem while my VM has 4 CPU cores

Here's what I encountered
![图片](https://user-images.githubusercontent.com/23524048/56912485-f1e4cb80-6ae1-11e9-815c-fa8b78d5eb96.png)

And the following is my version info
```bash
lx@ubuntu:~/contracts/hello$ uname -a
Linux ubuntu 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
lx@ubuntu:~/contracts/hello$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic
lx@ubuntu:~/contracts/hello$ eosio-cpp --version
eosio-cpp version 1.6.0
lx@ubuntu:~/contracts/hello$ eosio-abigen --version
eosio-abigen version 1.6.0
lx@ubuntu:~/contracts/hello$ g++ -v
Using built-in specs.
COLLECT_GCC=g++
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 
lx@ubuntu:~/contracts/hello$ clang++ -v
clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
Candidate multilib: .;@m64
Selected multilib: .;@m64
```

VM config as well (on VMware® Workstation 15 Pro)
![图片](https://user-images.githubusercontent.com/23524048/56912670-556ef900-6ae2-11e9-9383-3446ee8a1b40.png)

**Comment by LuminousXLB** [comment] 2019-04-30 05:59
> 
> 
> I hvae exactly the same problem while my VM has 4 CPU cores
> 
> Here's what I encountered
> ![图片](https://user-images.githubusercontent.com/23524048/56912485-f1e4cb80-6ae1-11e9-815c-fa8b78d5eb96.png)
> 
> And the following is my version info
> 
> ```shell
> lx@ubuntu:~/contracts/hello$ uname -a
> Linux ubuntu 4.18.0-15-generic #16~18.04.1-Ubuntu SMP Thu Feb 7 14:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
> lx@ubuntu:~/contracts/hello$ lsb_release -a
> No LSB modules are available.
> Distributor ID:	Ubuntu
> Description:	Ubuntu 18.04.2 LTS
> Release:	18.04
> Codename:	bionic
> lx@ubuntu:~/contracts/hello$ eosio-cpp --version
> eosio-cpp version 1.6.0
> lx@ubuntu:~/contracts/hello$ eosio-abigen --version
> eosio-abigen version 1.6.0
> lx@ubuntu:~/contracts/hello$ g++ -v
> Using built-in specs.
> COLLECT_GCC=g++
> COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/7/lto-wrapper
> OFFLOAD_TARGET_NAMES=nvptx-none
> OFFLOAD_TARGET_DEFAULT=1
> Target: x86_64-linux-gnu
> Configured with: ../src/configure -v --with-pkgversion='Ubuntu 7.3.0-27ubuntu1~18.04' --with-bugurl=file:///usr/share/doc/gcc-7/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-7 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
> Thread model: posix
> gcc version 7.3.0 (Ubuntu 7.3.0-27ubuntu1~18.04) 
> lx@ubuntu:~/contracts/hello$ clang++ -v
> clang version 6.0.0-1ubuntu2 (tags/RELEASE_600/final)
> Target: x86_64-pc-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
> Found candidate GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/8
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.3.0
> Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
> Selected GCC installation: /usr/bin/../lib/gcc/x86_64-linux-gnu/7.3.0
> Candidate multilib: .;@m64
> Selected multilib: .;@m64
> ```
> 
> VM config as well (on VMware® Workstation 15 Pro)
> ![图片](https://user-images.githubusercontent.com/23524048/56912670-556ef900-6ae2-11e9-9383-3446ee8a1b40.png)

I downgrade my cdt to v1.5.0, and everything is ok

**Comment by Will21375** [comment] 2019-05-03 07:14
> 
> I downgrade my cdt to v1.5.0, and everything is ok

Downgrading the cdt to v1.5.0 does not solve the problem for me. Instead of freezing during `eosio-cpp -abigen -o hello.wasm hello.cpp`, I now get this error: 
```
hello.cpp:1:10: fatal error: 'eosio/eosio.hpp' file not found
#include <eosio/eosio.hpp>
         ^~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by LuminousXLB** [comment] 2019-05-03 08:12
> 
> 
> > I downgrade my cdt to v1.5.0, and everything is ok
> 
> Downgrading the cdt to v1.5.0 does not solve the problem for me. Instead of freezing during `eosio-cpp -abigen -o hello.wasm hello.cpp`, I now get this error:
> 
> ```
> hello.cpp:1:10: fatal error: 'eosio/eosio.hpp' file not found
> #include <eosio/eosio.hpp>
>          ^~~~~~~~~~~~~~~~~
> 1 error generated.
> ```

I'm terribly sorry, but I used the sample contract from https://github.com/EOSIO/eosio.cdt/tree/v1.5.0/examples/hello
For your case, I recommend you upgrade your cdt to v1.6.1. I tried it and it works.

**Comment by Will21375** [comment] 2019-05-07 02:44
> For your case, I recommend you upgrade your cdt to v1.6.1. I tried it and it works.

Indeed. I confirm

**Comment by jeffreyssmith2nd** [comment] 2019-07-22 13:55
I'm closing this issue as the root cause of requiring at least 2 cores has been discovered and documented,

**Closed by jeffreyssmith2nd** 2019-07-22 13:55 UTC

**Comment by godmar** [comment] 2019-11-12 17:11
FWIW, this still happens with eosio-1.6.1.  It's reproducible on a single-core machine, but I just had it happen on a dual-core machine (more specifically, a 2 vCPU AWS t2.medium instance). 

Here's my process tree:
```
27808 ?        Ss     0:00  \_ sshd: ubuntu [priv]
27912 ?        S      0:00  |   \_ sshd: ubuntu@pts/1
27913 pts/1    Ss     0:00  |       \_ -bash
28235 pts/1    S+     0:02  |           \_ eosio-cpp --abigen addressbook_with_age_and_notify.cpp -o addressbook.wasm
28239 pts/1    S+     0:00  |               \_ sh -c /usr/opt/eosio.cdt/1.6.1/bin/eosio-ld  /tmp/addressbook_with_age_and_notify
28240 pts/1    S+     0:00  |                   \_ /usr/opt/eosio.cdt/1.6.1/bin/eosio-ld /tmp/addressbook_with_age_and_notify.cp
28241 pts/1    S+     0:00  |                       \_ sh -c /usr/opt/eosio.cdt/1.6.1/bin/wasm-ld --gc-sections --strip-all -zst
28242 pts/1    Sl+    0:00  |                           \_ /usr/opt/eosio.cdt/1.6.1/bin/wasm-ld --gc-sections --strip-all -zstac
```

`strace -p 28242` shows wasm-ld stuck in futex wait call (which could by any of pthread_cond_wait or sem_wait or similar).
```
futex(0x7ffdce2358c8, FUTEX_WAIT_PRIVATE, 0, NULL
```

It makes sense that whatever triggers this is just less likely to happen on a 2 core machine, yet still possible.

I googled and found one known bug in LLVM's multi-threaded linker, e.g. [here](https://bugs.llvm.org/show_bug.cgi?id=34806), but I do not know which version eosio.cdt is at.

**Comment by mrostamii** [comment] 2020-10-05 11:50
Thanks to @ciga2011 
It has solved by running `cleos-cpp` on an environment more than one core processor attached.
