### ISSUE TITLE
1.7.0 segfault on ecc_public_key

### ISSUE THREAD

**Issue by cc32d9** [EOSIO/eosio.cdt#790] opened 2020-01-17 21:42 UTC
The following code crashes the compiler. If I comment out `ecc_public_key pubkey;` line, it compiles.

```
#include <eosio/eosio.hpp>
#include <eosio/multi_index.hpp>
#include <eosio/crypto.hpp>
#include <eosio/time.hpp>


using namespace eosio;

CONTRACT sealregistry : public eosio::contract {
 public:
  sealregistry( name self, name code, datastream<const char*> ds ):
    contract(self, code, ds)
    {}
  
  ACTION newiid(uint64_t id, name owner)
  {
    require_auth(owner);
    issuerids _ids(_self, 0);
    auto itr = _ids.find(id);
    check( itr == _ids.end(), "This issuer ID already exists");
    _ids.emplace(owner, [&]( auto& item ) {
                          item.id = id;
                          item.owner = owner;
                        });
  }


  
  
 private:
   
  struct [[eosio::table("issuerids")]] issuerid {
    uint64_t       id;             /* unique ID assigned by issuer */
    name           owner;
    auto primary_key()const { return id; }
  };
    
  typedef eosio::multi_index<
    name("issuerids"), issuerid
    > issuerids;


  struct [[eosio::table("pubkeys")]] pubkey {
    uint64_t       id;             /* autoincrement */
    uint64_t       issuerid;       /* issuer account may have multiple issuer IDs */
    uint64_t       seq_start;      /* first sequence number of seals signed with key */
    uint64_t       seq_end;        /* last sequence number of seals signed with key */
    ecc_public_key pubkey;
    auto primary_key()const { return id; }
    uint128_t get_seqstart()const { return ((uint128_t) issuerid << 64) & ((uint128_t) seq_start); }
    uint128_t get_seqend()const { return ((uint128_t) issuerid << 64) & ((uint128_t) seq_end); }
  };

  typedef eosio::multi_index<
    name("pubkeys"), pubkey,
    indexed_by<name("seqstart"), const_mem_fun<pubkey, uint128_t, &pubkey::get_seqstart>>,
    indexed_by<name("seqend"), const_mem_fun<pubkey, uint128_t, &pubkey::get_seqend>>
    > pubkeys;
  
  
  struct [[eosio::table("seals")]] seal {
    uint64_t       id;             /* autoincrement */
    uint64_t       issuerid;
    uint64_t       seqnum;         /* unique sequence number within this issuer ID */
    checksum256    sighash;        /* sha256 of on-chip signature */
    time_point_sec expires;        /* before expiration date, only the recipient can delete an entry */
    uint64_t       workflow;
    name           status;         /* status field that is modified by issuer, transit and recipient */
    auto primary_key()const { return id; }
    uint128_t get_seq()const { return ((uint128_t) issuerid << 64) & ((uint128_t) seqnum); }
    uint64_t get_expires()const { return expires.utc_seconds; }
  };

  typedef eosio::multi_index<
    name("seals"), seal,
    indexed_by<name("seq"), const_mem_fun<seal, uint128_t, &seal::get_seq>>,
    indexed_by<name("expires"), const_mem_fun<seal, uint64_t, &seal::get_expires>>
    > seals;

  
  struct [[eosio::table("workflows")]] workflow {
    uint64_t       id;             /* autoincrement */
    uint64_t       issuerid;  
    uint64_t       workflow;       /* workflow ID assigned by issuer */
    name           transit;        /* account name of transport company */
    name           recipient;      /* account name of recipient */
    uint64_t       sealscnt;       /* number of seals in the workflow */
    auto primary_key()const { return id; }
    uint128_t get_workflow()const { return ((uint128_t) issuerid << 64) & ((uint128_t) workflow); }
  };

  typedef eosio::multi_index<
    name("workflowes"), workflow,
    indexed_by<name("workflow"), const_mem_fun<workflow, uint128_t, &workflow::get_workflow>>
    > workflowes;
  
};

  
```

**Comment by cc32d9** [comment] 2020-01-17 21:52
defining the member as `public_key     pubkey;` works too.  Probably the ABI generator does not how to handle a standalone `ecc_public_key`

**Comment by MrToph** [comment] 2020-01-20 12:35
Same here ...

**Comment by swatanabe-b1** [comment] 2020-01-23 20:33
This is a duplicate of #729.  The ABI generator fails on non-type template parameters.  ecc_public_key is a std::array.

**Closed** 2021-03-25 14:44 UTC
Labels: duplicate
