### ISSUE TITLE
compile token never finish

### ISSUE THREAD

**Issue by yanyiwu** [EOSIO/eosio.cdt#471] opened 2019-03-24 13:23 UTC
```
eosio-cpp -I include -o eosio.token.wasm src/eosio.toke.cpp --abigen
```
never finished. 

machine: ubuntu 18.04, 2 cores, so https://github.com/EOSIO/eosio.cdt/issues/288 do not help .

**Comment by yanyiwu** [comment] 2019-03-24 13:33
i am following the https://developers.eos.io/eosio-home/docs/token-contract tutorials to learn how to write eos contract, but i am stuck in this step.

**Comment by yanyiwu** [comment] 2019-03-24 13:35
@larryk85

**Comment by yanyiwu** [comment] 2019-03-24 13:48
the issue has been fixed after i upgraded eosio.cdt version from 1.6.0 to 1.6.1.

**Comment by yanyiwu** [comment] 2020-05-31 14:58
it happened again, even through eosio-cpp already be upgraded to v1.6.1 

eosio-cpp -v
clang version 7.0.0 (https://github.com/eosio/clang.git 6b886302a11a8419b76e469794ff9d0c531a4b4b) (https://github.com/eosio/llvm a41b8e7653258a4f1a5911ef28c95672efce051e)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /usr/opt/eosio.cdt/1.6.1/bin
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/8
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/7.4.0
Candidate multilib: .;@m64
Selected multilib: .;@m64

**Comment by yanyiwu** [comment] 2020-05-31 14:59
@larryk85 i need your help, thanks

**Comment by jeffreyssmith2nd** [comment] 2020-06-05 19:16
See issue #741, this can happen even with multiple CPUs. Regardless, PR #896 should resolve this issue.

I'm going to close this since the issue is being tracked on #741 and we have a fix incoming.

**Closed by jeffreyssmith2nd** 2020-06-05 19:16 UTC
