### ISSUE TITLE
wasm-ld: error: fatal failure: contract with no actions and trying to create dispatcher

### ISSUE THREAD

**Issue by elmato** [EOSIO/eosio.cdt#468] opened 2019-03-23 08:19 UTC
How to reproduce:

```c++
#include <eosio/eosio.hpp>
#include <eosio/name.hpp>
#include <eosio/asset.hpp>

using namespace eosio;

CONTRACT no_actions : public contract {
   public:
      using contract::contract;

      [[eosio::on_notify("eosio.token::transfer")]]
      void on_transfer( name from, name to, asset quantity, std::string  memo ) {
         eosio::print("eosio.token::transfer!");
      }
};
```

```bash
 eosio-cpp -o no_actions.wasm -contract no_actions no_actions.cpp

**wasm-ld: error: fatal failure: contract with no actions and trying to create dispatcher**
```

**Comment by slyon** [comment] 2019-04-17 10:58
I can see the same problem in my smart contract.

**Comment by zeeshanyousaf094** [comment] 2019-04-25 18:03
The problem is due to different with the file name and contract name.
Please update the contract name according to file name i.e if file name is "testcontract.cpp" The contract should be defined as:
class [[eosio::contract("testcontract")]] cafe : public eosio::contract {
}

**Comment by jeffreyssmith2nd** [comment] 2019-07-17 13:52
I'm seeing this on 1.6.2. Adding an empty action to the contract allows it to compile, though I don't think that's an optimal solution.

**Comment by saradach** [comment] 2019-09-25 05:41
I am still facing this issue. Any workaround?

**Comment by jeffreyssmith2nd** [comment] 2019-09-25 13:24
> I am still facing this issue. Any workaround?

If you're looking for a work around, you can just add an empty action to the contract. I do not believe an actual fix has been implemented yet.

**Comment by sterbon** [comment] 2019-10-09 16:50
The contract name and file name must be same.

**Comment by sterbon** [comment] 2019-10-09 16:51
The name of the contract and the name of the cpp file must be the same, this fixed my issue

**Comment by chipueatfast** [comment] 2019-10-27 08:05
> The problem is due to different with the file name and contract name.
> Please update the contract name according to file name i.e if file name is "testcontract.cpp" The contract should be defined as:
> class [[eosio::contract("testcontract")]] testcontract : public eosio::contract {
> }

can you explain why we have to do it, is it similar to the 'export default' syntax in javascript??

**Closed** 2021-03-25 14:35 UTC
Labels: bug
