### ISSUE TITLE
eosio-cpp compile never finish

### ISSUE THREAD

**Issue by vingo555** [EOSIO/eosio.cdt#288] opened 2018-11-17 07:07 UTC
I spend days to try to finger out the issue while i found the eosio.cdt is really bad.

Does any contributor really work on that to really help the community to develop well ?
Such simple sample and not able to work well.

I really feel frustrated. 

I want to ask those so called contributor some of question:
1. Did you really think about compatibility?
2. Even the sample not able to run well,  what is the meaning of other work ?

**Comment by vingo555** [comment] 2018-11-17 07:13
I think the issue i have is similar with  [Issue 123](https://github.com/EOSIO/eosio.cdt/issues/123) .

**Comment by ChrisCates** [comment] 2018-11-17 15:46
@vingo555, @neozju:

The team behind CDT has made hundreds of breaking changes with no backwards compatibility, the documentation does not reflect the changes made as well.

The library files do not reflect the library files found in the main eos repository either.
The type names have been completely rewritten, thus making it difficult to use the interpreter with original eos files.

I also find the EOS team(s) to be very eager to close tickets even when the commenter does not have their issue resolved.

Hopefully, the EOS team is aware that this kind of behaviour does not give a good impression to developers.

**Comment by ChrisCates** [comment] 2018-11-18 14:14
Majority of the eosiolib .hpp files have been rewritten and the breaking
changes are completely undocumented. There are no transitional documents
when clearly 90% of the eosiolib breaks on this update.

Majority of existing contracts currently in the ecosystem leverage the old
.hpp files and are “outdated”. Thus, if you want to send inline actions and
interact with them in a new contract, you need a reference to their
original eosiolib structure.

**Comment by vingo555** [comment] 2018-11-19 04:04
@larryk85 

Currently I never make the sample work. The environment that i have 👍 
1. My working environment may seem a little complicated.  The host OS is window 10 and run Ubuntu 18 under Vmware station.   Run on docker instance inside Ubuntu.  My understanding is those environment not really affect much but the software version really is a matter.

```bash
root@f0798f379071:/# nodeos --version
v1.3.1-dirty
root@f0798f379071:/#
```
I have tried with the latest version eosio.cdt (1.4.1) and also tried eosio.cdt(1.3.1).   The hello sample with CMake file can be compiled with version 1.4.1 and not work with version 1.3.1( this is not the issue i want to feedback), the issue is the compiler never finish.

When i manually input 
```bash
eosio-cpp -g hello.wasm hello.cpp --abigen
```
the compiler never return (never finish)
When i try to Ctrl+C to interrupt it after waiting for a very long time. I found hello.wasm is generated. while when i try to deploy the contract by command 

```bash
set contract hello ./hello -p hello@active
```

it will report the error: 
```cplusplus
FC_DECLARE_DERIVED_EXCEPTION( wasm_execution_error,     wasm_exception,
                                    3070002, "Runtime Error Processing WASM" )
```
i search the error code 3070002 inside the eosio source code, i believe the reason is the wasm file is not generated correctly.
i never even make one time deploy contract successfully.  

If you need more information, let me know.

BTW,  Do you know any docker have well work environment ?  I mean when i using that docker i can compile (EVEN the sample) the code and deploy successfully.

**Comment by ChrisCates** [comment] 2018-11-25 19:15
@rongbro, the eosio contracts migrated over to:
https://github.com/EOSIO/eosio.contracts

eos and the cdt repositories have out of date contracts, thus meaning
everything breaks even on a successful compile.

Hope that clears up any problems anyone else has...
They still haven't cleared up these problems in their `README.md` files
though...

**Comment by rongbro** [comment] 2018-11-26 03:05
@ChrisCates Just woke up and saw this, thanks for your reply.

Yep, various documents are not quite correct, the official website also has these problems.

Do you know these [https://github.com/EOSIO/eosio.cdt/tree/master/examples](examples), and are they always correct?

**Comment by rongbro** [comment] 2018-11-26 03:38
Thank you, get it ~~

**Comment by akrsmv** [comment] 2018-11-26 12:49
Just to confirm, that after me having the same 'freeze' issue on a vps *with only 1 CPU*, after switching to a vps with 2 cores, all works like a charm.

**Comment by larryk85** [comment] 2018-12-17 16:17
Yes, I have finally been able to replicate it.  The issue is that you need at least 2 cores or the linker will hang indefinitely.

**Comment by youngqqcn** [comment] 2018-12-30 08:12
- Thanks!   It's work for me!    Change the VM to 2 cores.
非常感谢! 我把虚拟改成2核就可以编译成功了!

**Comment by yanyiwu** [comment] 2019-03-24 09:16
So disappointed to see the solution is to increase core numbers ...

**Comment by zwebmedia** [comment] 2019-05-26 12:56
Guys, sincere thanks for EOS Studio and allowing free access and training, great contribution. So about a week ago I set out to conquer nations, and today I am still not able to get out the door. I ran the latest Windows installation, installed Docker, checked on-chip virtualization. Then Docker told me I needed Windows 10 Pro. I have Windows 8. I was able to install Docker Tools instead and everything installed fine. Imagine my surprise when I tried to build eosio.token and it never finished. Tweaked many things, finally a Google search landed me here. I found the wasm already built file and the other file needed on the web and put it in the folder so I could get past this problem, but that led to other errors. My friend tried to install on MacBook Pro and same problem, build never finishes. 

Please could you have some mercy on those of us mortals who are not Linux alchemists. There are some solutions above which mention more than one core. Ok great! What does it mean and how to do it? Following the Windows installation, any VM was installed in the background. How do I access it and how do I set the cores? Please could someone who knows a lot more than me go through this and document the procedure clearly? It's great that you are making training video #30 about some advanced topic, and thanks again for that, but there are perhaps thousands of us stuck on square one, cannot build the sample. Help please and thanks!

**Comment by zwebmedia** [comment] 2019-06-02 00:59
To set the cores on Windows, you double click on the "Oracle VM VirtualBox" icon that appeared on your desktop after Docker install. Go to "Settings", "System", "Processor". Slide the "Processor" slider to the right to select at least two cores. OK!

Spoiler alert! If the processor slider is greyed out, it means your processor only has one core, and can never be used to run a VM with two cores. And mine is greyed out. :(

Does anyone know how to set the cores on a Mac?

**Comment by jeffreyssmith2nd** [comment] 2019-07-22 13:46
@zwebmedia That sounds like a question for Virtualbox support.

I'm closing this issue as the root cause has been discovered and documented.

**Closed by jeffreyssmith2nd** 2019-07-22 13:46 UTC
